{% set name = "Flask-SQLAlchemy" %}
{% set version = "3.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/flask_sqlalchemy/flask_sqlalchemy-{{ version }}.tar.gz
  sha256: e4b68bb881802dda1a7d878b2fc84c06d1ee57fb40b874d3dc97dabfa36b8312

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - flit-core <4
  run:
    - python >=3.8
    - flask >=2.2.5
    - sqlalchemy >=2.0.16

test:
  imports:
    - flask_sqlalchemy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pallets/flask-sqlalchemy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Adds SQLAlchemy support to your Flask application
  dev_url: https://github.com/pallets/flask-sqlalchemy
  doc_url: https://flask-sqlalchemy.palletsprojects.com

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
