context:
  name: Flask-SQLAlchemy
  version: 3.1.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/f/flask_sqlalchemy/flask_sqlalchemy-${{ version }}.tar.gz
  sha256: e4b68bb881802dda1a7d878b2fc84c06d1ee57fb40b874d3dc97dabfa36b8312

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - flit-core <4
  run:
    - python >=${{ python_min }}
    - flask >=2.2.5
    - sqlalchemy >=2.0.16

tests:
  - python:
      imports:
        - flask_sqlalchemy
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Adds SQLAlchemy support to your Flask application
  homepage: https://github.com/pallets/flask-sqlalchemy
  repository: https://github.com/pallets/flask-sqlalchemy
  documentation: https://flask-sqlalchemy.palletsprojects.com

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors

